
# auto-launching ssh-agent for wsl
# source: https://docs.github.com/en/github/authenticating-to-github/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows

env=~/.ssh/agent.env

agent_load_env () { test -f "$env" && . "$env" >| /dev/null ; }

agent_start () {
     (umask 077; ssh-agent >| "$env")
     . "$env" >| /dev/null ; }

agent_load_env

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
agent_run_state=$(ssh-add -l >| /dev/null 2>&1; echo $?)

if [ ! "$SSH_AUTH_SOCK" ] || [ $agent_run_state = 2 ]; then
     agent_start
     ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ $agent_run_state = 1 ]; then
     ssh-add
fi

unset env

# can't figure out this fpath thing yet
#fpath+=~/.dotfiles/zsh/functions

source ~/.zsh_plugins.sh # Load zsh plugins
source ~/.dotfiles/zsh/env.zsh
source ~/.dotfiles/zsh/options.zsh
#source ~/.dotfiles/zsh/functions/functions.zsh
#source ~/.dotfiles/zsh/functions/fzf-functions.zsh
#source ~/.dotfiles/zsh/functions/git-functions.zsh
#source ~/.dotfiles/zsh/bindings.zsh
source ~/.dotfiles/zsh/alias.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$PATH"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/jc/.sdkman"
[[ -s "/home/jc/.sdkman/bin/sdkman-init.sh" ]] && source "/home/jc/.sdkman/bin/sdkman-init.sh"
